spring.application.name=riskintel
spring.datasource.url=jdbc:postgresql://localhost:5432/riskintel
spring.datasource.username=postgres
spring.datasource.password=Pratham@376

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
